version: "3.4"

networks:
  db_net:
    external: true
  default:

services:
  core:
    container_name: hack-core
    environment:
      - RUN_LEVEL=dev
    entrypoint:
      - uvicorn
      - services.core:app
      - --host=0.0.0.0
      - --reload
    build:
      context: supreme-spirit
      dockerfile: docker/Dockerfile.server
      target: dev
    volumes:
      - ./supreme-spirit:/opt/app
    networks:
      - default
    depends_on:
      - postgres
  postgres:
    container_name: hack-postgres
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: hack
    networks:
      - db_net
      - default
    volumes:
      - ./.docker_data/postgres:/var/lib/postgresql/data
  nginx:
    image: nginx:alpine
    container_name: hack-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - core
    networks:
      - default
  redis:
    image: redis
    networks:
      - default
    ports:
      - "6379:6379"
    container_name: hack-redis
