"""


Revision ID: 023d751d47e8
Revises: 7bd79b16bd4f
Create Date: 2019-12-07 06:11:44.486954

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '023d751d47e8'
down_revision = 'fc0d0df8c0cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('offers', 'offer_template_id', existing_type=sa.INTEGER(), nullable=False)
    op.alter_column('offers', 'user_id', existing_type=sa.INTEGER(), nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('offers', 'user_id', existing_type=sa.INTEGER(), nullable=True)
    op.alter_column('offers', 'offer_template_id', existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###
