"""


Revision ID: 11c42ddafcfa
Revises: 77ae1fa75e60
Create Date: 2019-12-07 06:41:02.039283

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11c42ddafcfa'
down_revision = '77ae1fa75e60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
