"""


Revision ID: 13f9ad8e2d2d
Revises: 930061a8ff79
Create Date: 2019-12-07 06:49:29.439590

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13f9ad8e2d2d'
down_revision = '930061a8ff79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bound_offer_templates',
    sa.Column('bound_offer_templates_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('offer_filter_id', sa.Integer(), nullable=True),
    sa.Column('offer_template_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['offer_filter_id'], ['offer_filters.offer_filter_id'], ),
    sa.ForeignKeyConstraint(['offer_template_id'], ['offer_templates.offer_template_id'], ),
    sa.PrimaryKeyConstraint('bound_offer_templates_id')
    )
    op.create_index(op.f('ix_bound_offer_templates_bound_offer_templates_id'), 'bound_offer_templates', ['bound_offer_templates_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bound_offer_templates_bound_offer_templates_id'), table_name='bound_offer_templates')
    op.drop_table('bound_offer_templates')
    # ### end Alembic commands ###
