"""


Revision ID: 1d231fedc8bb
Revises: 698e61d58523
Create Date: 2019-12-07 02:03:43.203163

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "1d231fedc8bb"
down_revision = "698e61d58523"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "offer_filters",
        sa.Column("offer_filter_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("filter", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.PrimaryKeyConstraint("offer_filter_id"),
    )
    op.create_index(
        op.f("ix_offer_filters_offer_filter_id"),
        "offer_filters",
        ["offer_filter_id"],
        unique=False,
    )
    op.create_table(
        "offer_templates",
        sa.Column("offer_template_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column(
            "type",
            sa.Enum("CREDIT", "DEPOSIT", "AUTOTRANSACTION", name="offertype"),
            nullable=True,
        ),
        sa.Column("text", sa.String(length=250), nullable=True),
        sa.Column("data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.PrimaryKeyConstraint("offer_template_id"),
    )
    op.create_index(
        op.f("ix_offer_templates_offer_template_id"),
        "offer_templates",
        ["offer_template_id"],
        unique=False,
    )
    op.create_table(
        "bound_offer_templates",
        sa.Column("bound_offer_templates_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("offer_filter_id", sa.Integer(), nullable=True),
        sa.Column("offer_template_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["offer_filter_id"], ["offer_filters.offer_filter_id"]),
        sa.ForeignKeyConstraint(
            ["offer_template_id"], ["offer_templates.offer_template_id"]
        ),
        sa.PrimaryKeyConstraint("bound_offer_templates_id"),
    )
    op.create_index(
        op.f("ix_bound_offer_templates_bound_offer_templates_id"),
        "bound_offer_templates",
        ["bound_offer_templates_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_bound_offer_templates_bound_offer_templates_id"),
        table_name="bound_offer_templates",
    )
    op.drop_table("bound_offer_templates")
    op.drop_index(
        op.f("ix_offer_templates_offer_template_id"), table_name="offer_templates"
    )
    op.drop_table("offer_templates")
    op.drop_index(op.f("ix_offer_filters_offer_filter_id"), table_name="offer_filters")
    op.drop_table("offer_filters")
    # ### end Alembic commands ###
