"""


Revision ID: 698e61d58523
Revises: 776cc0dac452
Create Date: 2019-12-07 01:09:16.085294

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "698e61d58523"
down_revision = "776cc0dac452"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "transactions",
        sa.Column("transaction_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("amount", sa.BigInteger(), nullable=True),
        sa.PrimaryKeyConstraint("transaction_id"),
    )
    op.create_index(
        op.f("ix_transactions_transaction_id"),
        "transactions",
        ["transaction_id"],
        unique=False,
    )
    op.add_column("accounts", sa.Column("account_id", sa.Integer(), nullable=False))
    op.add_column("accounts", sa.Column("created_at", sa.DateTime(), nullable=True))
    op.create_index(
        op.f("ix_accounts_account_id"), "accounts", ["account_id"], unique=False
    )
    op.drop_index("ix_accounts_user_id", table_name="accounts")
    op.drop_column("accounts", "user_id")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "accounts",
        sa.Column("user_id", sa.INTEGER(), autoincrement=True, nullable=False),
    )
    op.create_index("ix_accounts_user_id", "accounts", ["user_id"], unique=False)
    op.drop_index(op.f("ix_accounts_account_id"), table_name="accounts")
    op.drop_column("accounts", "created_at")
    op.drop_column("accounts", "account_id")
    op.drop_index(op.f("ix_transactions_transaction_id"), table_name="transactions")
    op.drop_table("transactions")
    # ### end Alembic commands ###
