"""


Revision ID: 6d7c1cc87620
Revises: 1d231fedc8bb
Create Date: 2019-12-07 02:37:27.852050

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d7c1cc87620'
down_revision = '1d231fedc8bb'
branch_labels = None
depends_on = None


def upgrade():
    op.create_unique_constraint(None, 'accounts', ['account_id'])
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'accounts', 'users', ['user_id'], ['user_id'])
    op.add_column('transactions', sa.Column('from_account_id', sa.Integer(), nullable=True))
    op.add_column('transactions', sa.Column('from_user_id', sa.Integer(), nullable=True))
    op.add_column('transactions', sa.Column('to_account_id', sa.Integer(), nullable=True))
    op.add_column('transactions', sa.Column('to_user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'transactions', 'users', ['from_user_id'], ['user_id'])
    op.create_foreign_key(None, 'transactions', 'accounts', ['to_account_id'], ['account_id'])
    op.create_foreign_key(None, 'transactions', 'accounts', ['from_account_id'], ['account_id'])
    op.create_foreign_key(None, 'transactions', 'users', ['to_user_id'], ['user_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_column('transactions', 'to_user_id')
    op.drop_column('transactions', 'to_account_id')
    op.drop_column('transactions', 'from_user_id')
    op.drop_column('transactions', 'from_account_id')
    op.drop_constraint(None, 'accounts', type_='foreignkey')
    op.drop_column('accounts', 'user_id')
    # ### end Alembic commands ###
