"""


Revision ID: 776cc0dac452
Revises: 
Create Date: 2019-12-07 00:59:37.881713

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "776cc0dac452"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "accounts",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "type",
            sa.Enum("CREDIT", "DEPOSIT", "PAYMENT", name="accounttype"),
            nullable=True,
        ),
        sa.Column("currency", sa.String(length=20), nullable=True),
        sa.Column("balance", sa.BigInteger(), nullable=True),
        sa.Column("interest", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_index(op.f("ix_accounts_user_id"), "accounts", ["user_id"], unique=False)
    op.create_table(
        "users",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("login", sa.String(length=50), nullable=False),
        sa.Column("address", sa.String(length=50), nullable=True),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_index(op.f("ix_users_user_id"), "users", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_user_id"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_accounts_user_id"), table_name="accounts")
    op.drop_table("accounts")
    # ### end Alembic commands ###
