"""


Revision ID: 77ae1fa75e60
Revises: a5c9dea2f90e
Create Date: 2019-12-07 06:36:51.638386

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77ae1fa75e60'
down_revision = 'a5c9dea2f90e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
