"""


Revision ID: 930061a8ff79
Revises: 11c42ddafcfa
Create Date: 2019-12-07 06:41:56.211226

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '930061a8ff79'
down_revision = '11c42ddafcfa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
