"""


Revision ID: 94657cdcf068
Revises: d7ab04b70bff
Create Date: 2019-12-07 06:30:54.198499

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94657cdcf068'
down_revision = 'd7ab04b70bff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
