"""


Revision ID: a5c9dea2f90e
Revises: 94657cdcf068
Create Date: 2019-12-07 06:34:31.107788

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5c9dea2f90e'
down_revision = '94657cdcf068'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
