"""


Revision ID: baad9816473f
Revises: 540dda9fd8ea
Create Date: 2019-12-07 20:28:35.944255

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'baad9816473f'
down_revision = '540dda9fd8ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offers', sa.Column('accepted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('offers', 'accepted')
    # ### end Alembic commands ###
