"""


Revision ID: c44cebb195d6
Revises: 
Create Date: 2019-12-07 05:20:47.677137

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c44cebb195d6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'offer_filters',
        sa.Column('offer_filter_id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('filter', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.PrimaryKeyConstraint('offer_filter_id'),
    )
    op.create_index(
        op.f('ix_offer_filters_offer_filter_id'), 'offer_filters', ['offer_filter_id'], unique=False
    )
    op.create_table(
        'offer_templates',
        sa.Column('offer_template_id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column(
            'type', sa.Enum('CREDIT', 'DEPOSIT', 'AUTOTRANSACTION', name='offertype'), nullable=True
        ),
        sa.Column('text', sa.String(length=250), nullable=True),
        sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.PrimaryKeyConstraint('offer_template_id'),
    )
    op.create_index(
        op.f('ix_offer_templates_offer_template_id'),
        'offer_templates',
        ['offer_template_id'],
        unique=False,
    )
    op.create_table(
        'users',
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('login', sa.String(length=50), nullable=False),
        sa.Column('address', sa.String(length=50), nullable=True),
        sa.PrimaryKeyConstraint('user_id'),
        sa.UniqueConstraint('login'),
    )
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    op.create_table(
        'accounts',
        sa.Column('account_id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('name', sa.String(length=20), nullable=True),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column(
            'type', sa.Enum('CREDIT', 'DEPOSIT', 'PAYMENT', name='accounttype'), nullable=True
        ),
        sa.Column('currency', sa.String(length=20), nullable=True),
        sa.Column('balance', sa.BigInteger(), nullable=True),
        sa.Column('interest', sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.user_id']),
        sa.PrimaryKeyConstraint('account_id'),
    )
    op.create_index(op.f('ix_accounts_account_id'), 'accounts', ['account_id'], unique=False)
    op.create_table(
        'bound_offer_templates',
        sa.Column('bound_offer_templates_id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('offer_filter_id', sa.Integer(), nullable=True),
        sa.Column('offer_template_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['offer_filter_id'], ['offer_filters.offer_filter_id']),
        sa.ForeignKeyConstraint(['offer_template_id'], ['offer_templates.offer_template_id']),
        sa.PrimaryKeyConstraint('bound_offer_templates_id'),
    )
    op.create_index(
        op.f('ix_bound_offer_templates_bound_offer_templates_id'),
        'bound_offer_templates',
        ['bound_offer_templates_id'],
        unique=False,
    )
    op.create_table(
        'transactions',
        sa.Column('transaction_id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('from_user_id', sa.Integer(), nullable=True),
        sa.Column('to_user_id', sa.Integer(), nullable=True),
        sa.Column('from_account_id', sa.Integer(), nullable=True),
        sa.Column('to_account_id', sa.Integer(), nullable=True),
        sa.Column('amount', sa.BigInteger(), nullable=True),
        sa.ForeignKeyConstraint(['from_account_id'], ['accounts.account_id']),
        sa.ForeignKeyConstraint(['from_user_id'], ['users.user_id']),
        sa.ForeignKeyConstraint(['to_account_id'], ['accounts.account_id']),
        sa.ForeignKeyConstraint(['to_user_id'], ['users.user_id']),
        sa.PrimaryKeyConstraint('transaction_id'),
    )
    op.create_index(
        op.f('ix_transactions_transaction_id'), 'transactions', ['transaction_id'], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_transaction_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(
        op.f('ix_bound_offer_templates_bound_offer_templates_id'),
        table_name='bound_offer_templates',
    )
    op.drop_table('bound_offer_templates')
    op.drop_index(op.f('ix_accounts_account_id'), table_name='accounts')
    op.drop_table('accounts')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_offer_templates_offer_template_id'), table_name='offer_templates')
    op.drop_table('offer_templates')
    op.drop_index(op.f('ix_offer_filters_offer_filter_id'), table_name='offer_filters')
    op.drop_table('offer_filters')
    # ### end Alembic commands ###
