"""


Revision ID: d7ab04b70bff
Revises: 023d751d47e8
Create Date: 2019-12-07 06:24:00.800912

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7ab04b70bff'
down_revision = '023d751d47e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
