"""


Revision ID: f033ff684de9
Revises: 13f9ad8e2d2d
Create Date: 2019-12-07 08:57:11.195952

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f033ff684de9'
down_revision = '13f9ad8e2d2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
