"""


Revision ID: fc0d0df8c0cf
Revises: c44cebb195d6
Create Date: 2019-12-07 05:57:25.684488

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'fc0d0df8c0cf'
down_revision = 'c44cebb195d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'offers',
        sa.Column('offer', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('offer_template_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['offer_template_id'], ['offer_templates.offer_template_id']),
        sa.ForeignKeyConstraint(['user_id'], ['users.user_id']),
        sa.PrimaryKeyConstraint('offer'),
    )
    op.create_index(op.f('ix_offers_offer'), 'offers', ['offer'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_offers_offer'), table_name='offers')
    op.drop_table('offers')
    # ### end Alembic commands ###
